config/routes.rb
Rails.application.routes.draw do

  root 'ppirl#index'

  get 'view' => 'ppirl#view'
  post 'upload' => 'ppirl#upload'
  post 'update' => 'ppirl#update'
  post 'update_match' => 'ppirl#update_match'
  post 'go_next' => 'ppirl#go_next'
  post 'go_prev' => 'ppirl#go_prev'
  post 'finish' => 'ppirl#finish'

end

app/helpers/ppirl_helper.rb
require 'set'
module PpirlHelper
  

def find_duplicates(elements)
    encountered = {}
	arr = []
    # Examine all elements in the array.
    elements.each do |e|
	# If the element is in the hash, it is a duplicate.
	if encountered[e]
	    arr << e
	else
	    # Record that the element was encountered.
	    encountered[e] = 1
	end
    end
	return arr
end

def automatic_linkage (file_paths)
  $first_line = File.foreach(file_paths[0]).first
  $column_names = $first_line.strip.split(',')
  $num_cols = $column_names.size
  $rows_arr = [0,0]  # initialize to 0 so that rows from db do not keep appending when uploading file again w/o restarting server
  $totaldb = [] # initialize to 0 so that totalrows from db(db1+db2) do not keep appending when uploading file again w/o restarting server
  $totaldb1 = [] # initialize to 0 so that totalrows from db1 do not keep appending when uploading file again w/o restarting server
  $totaldb2 = [] # initialize to 0 so that totalrows from db2 do not keep appending when uploading file again w/o restarting server
  block_var1 = "reg_num"
  block_var2 = "fname"
  link_var = Array[block_var1, block_var2, "lname", "dob"]
  matched = Set.new
  unmatched = Set.new
  uncertain = Set.new
  #$value = Hash.new{|h, k| h[k] = []}
  block_hash1 = Hash.new{|h, k| h[k] = []} # hash for storing the tuples which have block var1
  block_hash2 = Hash.new{|h, k| h[k] = []} # hash for storing the tuples which have block va2r
  tuple_count = Hash.new(0)				   # hash for counting the number of duplicate tuples
  tuple_table = Hash.new{|h, k| h[k] = []} # hash for counting the tables in which this tuple exists
  graph = Hash.new{|h, k| h[k] = []}	   # adjacency list for graph to run DFS (connected components)
  
  $first_line = File.foreach(file_paths[0]).first
  $col_names = $first_line.strip.split(',')
  $col_num = $col_names.size
  puts "$col_num= #{$col_names}\n"
  puts "$col_num= #{$col_num}\n"
  block_index1 = $col_names.index(block_var1) - 1 # index of block var 1 in table
  block_index2 = $col_names.index(block_var2) - 1 # index of block var 2 in table

 
  for i in 0..file_paths.size-1 # loop through array of input files
	 File.foreach(file_paths[i]).drop(1).each_slice(1) do |line|
#    File.foreach(file_paths[i]) do |line|
	  #puts "line[0]= #{line[0]}\n"
    tuple = line[0].strip.split(",")
	  tuple.slice!(0)
	  #puts "tuple[0]= #{tuple[0]}\n"
	  #puts "tuple[1]= #{tuple[1]}\n"
	  #puts "tuple[2]= #{tuple[2]}\n"
	  #puts "tuple[3] #{tuple[3]}\n"
	  #puts "tuple[4]= #{tuple[4]}\n"
	  #puts "tuple[5]= #{tuple[5]}\n"
	  $totaldb << tuple;
	  $rows_arr[i] += 1
	  if i == 0
	    $totaldb1 << tuple;
	  else
	    $totaldb2 << tuple;
	  end
	  if(!tuple[block_index1].blank?)
      block_hash1[tuple[block_index1]] << tuple 
    end
    if(!tuple[block_index2].blank?)
      block_hash2[tuple[block_index2]] << tuple  
    end
	  tuple_count[tuple] += 1
	  if !(tuple_table[tuple].include? i+1) 
	    tuple_table[tuple] << i+1 
	  end
   end
  end
  
  block_hash1.keys.each do |key|
    #puts "#{key}-----"
	#puts "block_hash1[key].size= #{block_hash1[key].size}\n"
	if block_hash1[key].size == 1 # this id has no matching row, its single
      unmatched << block_hash1[key]		
	  next
	end

	# remove duplicate elements
	dup = find_duplicates(block_hash1[key])
	block_hash1[key].uniq!
	dup.each do |v|
		if block_hash1[key].include? v
			block_hash1[key].delete(v)
			$duplicates += 2
		end
	end
	#puts "block_hash1[key].size= #{block_hash1[key].size}\n"
	#puts "block_hash1[key]= #{block_hash1[key]}\n"

    for i in 0..block_hash1[key].size-2
	  for j in 1..block_hash1[key].size-1
		flag = 0
        for k in 0..$col_num-2
          if block_hash1[key][i][k] != block_hash1[key][j][k]
            flag = 1
            break
          end
        end
        if flag == 0
          matched << block_hash1[key][i]
        else
          uncertain << block_hash1[key][i]  
          uncertain << block_hash1[key][j] 
		  graph[block_hash1[key][i]] << block_hash1[key][j]
		  graph[block_hash1[key][j]] << block_hash1[key][i]
		end
	  end 
    end
	
  end
  
  block_hash2.keys.each do |key|
    #puts "#{key}-----"
	#puts "block_hash2[key].size= #{block_hash2[key].size}\n"
	
	if block_hash2[key].size == 1 # this id has no matching row, its single
      unmatched << block_hash2[key]  
	  next
	end
	
	dup = find_duplicates(block_hash2[key])
	#puts "DUPLICATE= #{dup}\n"
	#puts "DUPLICATESIZE= #{dup.size}\n"
	block_hash2[key].uniq!
	dup.each do |v|
		if block_hash2[key].include? v
			block_hash2[key].delete(v)
			$duplicates += 2
		end
	end
	#puts "block_hash2[key].size= #{block_hash2[key].size}\n"
	#puts "block_hash2[key]= #{block_hash2[key]}\n"
 
   for i in 0..block_hash2[key].size-2
		#puts "i = #{i}\n"
	  if unmatched.include? block_hash2[key][i]
        unmatched.delete? block_hash2[key][i]
	  end
	  for j in i+1..block_hash2[key].size-1
		#puts "j = #{j}\n"
		flag = 0
        for k in 0..$col_num-2
          if block_hash2[key][i][k] != block_hash2[key][j][k]
            flag = 1
            break
          end
        end
        if flag == 0
          matched << block_hash2[key][i]  
        else
          uncertain << block_hash2[key][i]  
          uncertain << block_hash2[key][j] 
		  #puts "block_hash2[key][i]= #{block_hash2[key][i]}\n"
		  #puts "block_hash2[key][j]= #{block_hash2[key][j]}\n"
		  graph[block_hash2[key][i]] << block_hash2[key][j]
		  graph[block_hash2[key][j]] << block_hash2[key][i]
		  
		  if unmatched.include? block_hash2[key][j]
            unmatched.delete? block_hash1[key][j]
		  end
		end
	  end 
    end
	
  end

  puts "graph - adjacency list\n"
  graph.each do |key, value|
	#puts "key = #{key}"
	#puts "value = #{value}\n"
  end
=begin
  puts "matched\n"
  matched.each do |val|
    puts "value = #{val}\n"
  end
  puts "unmatched\n"
  unmatched.each do |val|
    puts "value = #{val}\n"
  end
  puts "uncertain\n"
  uncertain.each do |val|
    puts "value = #{val}\n"
  end
=end

	#DFS on graph

	color = Hash.new{|h, k| h[k] = []} # hash for storing the color status of node
	cluster = Hash.new{|h, k| h[k] = []} # hash for storing the connected components/clusters
	graph.each do |key, value|
		color[key] = 'W';	
	end
	label = 0
	graph.each do |key, value|
		if(color[key] == 'W') 
			label = label + 1
			DFS(key, label, color, cluster, graph)
		end
	end
	
	puts "CLUSTER\n"
	cluster.each do |key, value|
		#puts "key = #{key}"
		#puts "value = #{value}\n"
		value.each do |val|
			#puts "val = #{val}\n"
			val.each do |v|
				#puts "v = #{v}\n"
			end
		end
			
	end
	
	return cluster

end

def DFS(node, label, color, cluster, graph)
	color[node] = 'G'
	cluster[label] << node
	graph[node].each do |v|
		if color[v] == 'W'
			DFS(v, label, color, cluster, graph)
		end
	end
	color[node] = 'B'
end


#file_paths = Array["/home/guest/Desktop/DirectedStudies/test-automatic1.csv","/home/guest/Desktop/DirectedStudies/test-automatic2.csv"]
#file_paths = Array["/home/guest/Desktop/DirectedStudies/db0709-small.csv","/home/guest/Desktop/DirectedStudies/db0829-small.csv"]
#automatic_linkage(file_paths)

  
  
  
  def get_edit_distance(s1, s2)
    finalStr1 = ""
    finalStr2 = ""
    
    if ((s1.blank?) || (s2.blank?))
      return "Miss",""
    end
=begin
    if ((s1.blank?) && (s2.blank?))
      return finalStr1, finalStr2
    end
    
    if(s1.blank?)
        return finalStr1, s2
    end
    if(s2.blank?)
        return s1, finalStr2
    end
=end
    
    
    len1 = s1.length
    len2 = s2.length
    

    dp = Hash.new{|h, k| h[k] = []}
    direction = Hash.new{|h, k| h[k] = []}

    for i in 0..len1
      for j in 0..len2
        if i == 0
          dp[i][j] = j
          direction[i][j] = 'd'
        elsif j == 0
          dp[i][j] = i
          direction[i][j] = 'i'
        elsif s1[i - 1] == s2[j - 1]
          dp[i][j] = dp[i - 1][j - 1]
          direction[i][j] = 'n'
        else
          insertVal = dp[i - 1][j]
          deleteVal = dp[i][j - 1]
          subsVal = dp[i - 1][j - 1]

          transVal = 1000000000
          if i > 1 and j > 1 and s1[i - 1] == s2[j - 2] and s1[i - 2] == s2[j - 1]
            transVal = dp[i - 2][j - 2]
          end

          minAll = [insertVal, deleteVal, subsVal, transVal].min

          if minAll == transVal
              direction[i][j] = 't'
          elsif minAll == insertVal
              direction[i][j] = 'i'
          elsif minAll == deleteVal
              direction[i][j] = 'd'
          else
              direction[i][j] = 's'
          end
          dp[i][j] = minAll + 1
        end
      end
    end

    
    stI = len1
    stJ = len2
    while stI > 0 or stJ > 0
      if direction[stI][stJ] == 'i'
        finalStr1 = s1[stI - 1] + finalStr1
        finalStr2 = " " + finalStr2
        stI = stI - 1

      elsif direction[stI][stJ] == 'd'
        finalStr1 = " " + finalStr1
        finalStr2 = s2[stJ -1] + finalStr2
        stJ = stJ - 1

      elsif direction[stI][stJ] == 's'
        finalStr1 = s1[stI -1] + finalStr1
        finalStr2 = s2[stJ - 1] + finalStr2
        stI = stI - 1
        stJ = stJ - 1

      elsif direction[stI][stJ] == 'n'
        finalStr1 = "-" + finalStr1
        finalStr2 = "-" + finalStr2
        stI = stI - 1
        stJ = stJ - 1

      else
        finalStr1 = "TX" + finalStr1
        finalStr2 = "TX" + finalStr2
        stI = stI - 2
        stJ = stJ - 2
      end
    end

    #puts finalStr1, finalStr2

    return finalStr1, finalStr2
  end

  # This is a private fucntion. Not for public use.
  # Returns
  # true if any key in the hash is a subset of the set provided.
  # false otherwise.
  def contains(hash, set)
    hash.each do |this_set, cnt|
      if this_set.subset? set
        return true
      end
    end
    return false
  end

  def apriori_algorithm(totaldb, threshold)
    ans = Hash.new
    threshold = threshold.to_i
    # This creates the set/actually hash of size 1
    hash = Hash.new
    hash.default = 0
    

app/views/ppirl/index.html.erb
<% provide(:title, 'DB') %>
<%= flash[:notice] %>
<div>
  <%= form_tag upload_path, multipart: true do %>
    <p>
      Upload an input CSV file1:<br />
      <%= file_field_tag :file1 %>
    </p>
    <p>
      Upload an input CSV file2:<br />
      <%= file_field_tag :file2 %>
    </p>
    <p>
      Enter the value of threshold 'K':<br />
      <%= text_field_tag :threshold, value=5 %>
    </p>
    <p>
      <%= submit_tag 'Submit' %>
    </p>
  <% end %>
</div>

app/views/ppirl/view.html.erb
<style type="text/css">
    table.center {
        margin-left: auto;
        margin-right: auto;
    }
    #mydiv {
        position: fixed;
        left: 50%;
    }
</style>

<script>
function onClickFucntion(row_num, col_num) {
    $.ajax(
            {
                type: 'POST',
                url: '/update',
                data: {
                    row: row_num,
                    column: col_num
                },
            }
    );
    window.location.href='/view?reload=0';
}
function updateMatchFucntion(row_num, already_matched) {
    $.ajax(
            {
                type: 'POST',
                url: '/update_match',
                data: {
                    row: row_num,
                    matched: already_matched
                },
            }
    );
    window.location.href='/view?reload=0';
}
function goPrevious() {
    $.ajax(
            {
                type: 'POST',
                url: '/go_prev',
            }
    );
    window.location.href='/view?reload=0';
}
function goNext() {
    $.ajax(
            {
                type: 'POST',
                url: '/go_next',
            }
    );
    window.location.href='/view?reload=0';
}

function finishLink(){
    $.ajax(
            {
                type: 'POST',
                url: '/finish',
            }
    );
    window.location.href='/view?reload=0';
}

</script>
<div>
<h3 class="alignleft">Total Rows in DB1: <%= $rows_arr[0] %> (dup= <%= $autolinked1 %>, unique= <%= $rows_arr[0]-$autolinked1 %>, rem= <%= $rows_arr[0]-$autolinked1-$autolinked %>)</h3>
<h3 class="alignright">Total Rows in DB2: <%= $rows_arr[1] %> (dup= <%= $autolinked2 %>, unique= <%= $rows_arr[1]-$autolinked2 %>, rem= <%= $rows_arr[1]-$autolinked2-$autolinked %>)</h3>
<div style="clear: both;"></div>
</div>
<div>
<h3 class="alignleft">Total automatically linked rows: <%= $autolinked %></h3>
<h3 class="alignright">Total uncertain matches: <%= $num_rows %></h3>
<div style="clear: both;"></div>
</div>
<div>
<h3 class="alignleft">Threshold: <%= $threshold %></h3>
<h3 class="alignright">Rare set size: <%= $all_rare_sets.size %></h3>
<div style="clear: both;"></div>
</div>
<div>
<h3 class="alignleft" id="response_message">Response message : <%= $message %></h3>
<h2 class="alignright">Privacy budget: <%= ($privacy_budget).round(2) %></h2>
<div style="clear: both;"></div>
</div>


<font size="5">
<table border="2" class="center">
  <thead>
    <tr>
      <th>cluster</th>
      <% for i in 1..$num_cols-1 %>
        <th><%= $column_names[i] %></th>
      <% end %>
      <th>Match</th>
    </tr>
  </thead>

  <% for row in $start_index..[$start_index + $gap, $num_rows - 1].min %>
  <tr>
    <td><%= $cluster_num[row] %></td>
    <% for col in 0..$num_cols - 2 %>
        <% if $values_first_shown[row][col] == $values_second_shown[row][col] %>
            <td onclick="onClickFucntion(<%= row %>, <%= col %>)"><%= $values_first_shown[row][col] %></td>
        <% else %>
            <td>
              <table>
                <tr><td onclick="onClickFucntion(<%= row %>, <%= col %>)"><%= $values_first_shown[row][col] %></td></tr>
                <tr><td onclick="onClickFucntion(<%= row %>, <%= col %>)"><%= $values_second_shown[row][col] %></td></tr>
              </table>
            </td>
        <% end %>
    <% end %>


    <td onclick="updateMatchFucntion(<%= row %>, <%= $is_match[row] == "true" %>)">
      <% if $is_match[row] == "true" %>
          Match
      <% else %>
          Not match
      <% end %>
    </td>

  </tr>
  <% end %>

</table>
<div id="mydiv">
    <button class="button" onclick="goPrevious()">Previous</button>
    <button class="button" onclick="goNext()">Next</button>
    <button class="button" onclick="finishLink()">FINISH</button>
</div>

</font>